// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-kuprzae4SNxA6NWUxiqvYbobkbXvdJs',
    appId: '1:222936818676:web:1b34c7c8fdbda4bcea8fa1',
    messagingSenderId: '222936818676',
    projectId: 'dime-meridian',
    authDomain: 'dime-meridian.firebaseapp.com',
    storageBucket: 'dime-meridian.firebasestorage.app',
    measurementId: 'G-DJGX58JKM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8RtSCVWm-V2tcexOZrTA65jVn7h3Ua1M',
    appId: '1:222936818676:android:5338bbda8083d1c4ea8fa1',
    messagingSenderId: '222936818676',
    projectId: 'dime-meridian',
    storageBucket: 'dime-meridian.firebasestorage.app',
  );

}